### PR TITLE
update superdesk-client dep and try to make it work

### PR DESCRIPTION
**Pull request by actionless**

### CODE REVIEW

**Comment by actionless** [comment]
@Flowdeeps @thnkloud9 please take a look on it, currently it can't load some of the superdesk templates, i did not found a way to fix that atm

**Comment by thnkloud9** [comment]
bower dep should be working here, but requires this PR to be merged in the superdesk repo first:

https://github.com/superdesk/superdesk/pull/1379

I also refactored to prepare for removal of requirejs as a dependency.  All angular components now have their own respective js files.

**Comment by thnkloud9** [comment]
superdesk has merged my changes, so this change is ready to go once it has been reviewed.  @actionless @Flowdeeps can you please review.

**Comment by actionless** [comment]
it fails on `grunt build`:

```
frontend_1 | Running "requirejs:compile" (requirejs) task
frontend_1 | Error: ENOENT, no such file or directory '/opt/superdesk-client/app/scripts/superdesk/superdesk.js'
frontend_1 | In module tree:
frontend_1 |     main
frontend_1 |
frontend_1 | { [Error: Error: ENOENT, no such file or directory '/opt/superdesk-client/app/scripts/superdesk/superdesk.js'
frontend_1 | In module tree:
frontend_1 |     main
frontend_1 |
frontend_1 |     at Object.fs.openSync (fs.js:432:18)
frontend_1 | ]
frontend_1 |   originalError:
frontend_1 |    { [Error: ENOENT, no such file or directory '/opt/superdesk-client/app/scripts/superdesk/superdesk.js']
frontend_1 |      errno: 34,
frontend_1 |      code: 'ENOENT',
frontend_1 |      path: '/opt/superdesk-client/app/scripts/superdesk/superdesk.js',
frontend_1 |      syscall: 'open',
frontend_1 |      fileName: '/opt/superdesk-client/app/scripts/superdesk/superdesk.js',
frontend_1 |      moduleTree: [ 'main' ] } }
```

**Comment by thnkloud9** [comment]
ah, I don't think we need this requirejs optimizer for the build anymore, and I would like to get rid of requirejs totally.  Any objections to me removing it from the Gruntfile?

**Comment by actionless** [comment]
now it's starting but i can't open 'Settings' section

**Pull request closed without merging**
